# pnpm workspace 定义 — Vue3 中后台前端平台 Monorepo

packages:
  # 共享包
  - 'packages/*'
  # 应用包
  - 'apps/*'

catalog:
  # —— 运行时核心依赖 ——
  vue: ^3.5
  pinia: ^2.2
  vue-router: ^4.4
  vue-i18n: ^10

  # —— UI 组件库 ——
  element-plus: ^2.9

  # —— 构建工具 ——
  vite: ^8.0
  vue-tsc: ^2.2
  '@vitejs/plugin-vue': ^5.2

  # —— 网络 & Mock & 服务端状态 ——
  ky: ^1
  msw: ^2.5
  '@tanstack/vue-query': ^5

  # —— 测试 ——
  '@vue/test-utils': ^2.4

  # —— 图表 ——
  '@antv/g2': ^5.2

  # —— 工作流 ——
  bpmn-js: ^17.0

overrides:
  eslint: '9.39.4'
  jsdom: '29.1.0'
  sass: '1.99.0'
  typescript: '6.0.3'
  vitest: '4.1.5'
