import type { RouteRecordRaw } from 'vue-router'

export const staticRoutes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('../views/login/index.vue'),
    meta: { title: '登录', hidden: true },
  },
  {
    path: '/',
    component: () => import('../layout/index.vue'),
    redirect: '/home',
    children: [
      {
        path: 'home',
        name: 'Home',
        component: () => import('../views/Home.vue'),
        meta: { title: '首页', icon: 'home', affix: true },
      },
      {
        path: 'profile',
        name: 'Profile',
        component: () => import('../views/profile/index.vue'),
        meta: { title: '个人中心', hidden: true },
      },
    ],
  },
]

export const asyncRoutes: RouteRecordRaw[] = [
  {
    path: '/system',
    component: () => import('../layout/index.vue'),
    meta: { title: '系统管理', icon: 'setting' },
    children: [
      {
        path: 'user',
        name: 'SystemUser',
        component: () => import('../views/system/user/index.vue'),
        meta: { title: '用户管理', icon: 'user' },
      },
      {
        path: 'role',
        name: 'SystemRole',
        component: () => import('../views/system/role/index.vue'),
        meta: { title: '角色管理', icon: 'usergroup' },
      },
      {
        path: 'menu',
        name: 'SystemMenu',
        component: () => import('../views/system/menu/index.vue'),
        meta: { title: '菜单管理', icon: 'list' },
      },
      {
        path: 'dept',
        name: 'SystemDept',
        component: () => import('../views/system/dept/index.vue'),
        meta: { title: '部门管理', icon: 'organization' },
      },
      {
        path: 'post',
        name: 'SystemPost',
        component: () => import('../views/system/post/index.vue'),
        meta: { title: '岗位管理', icon: 'bookmark' },
      },
      {
        path: 'dict',
        name: 'SystemDict',
        component: () => import('../views/system/dict/index.vue'),
        meta: { title: '字典管理', icon: 'file' },
      },
      {
        path: 'notice',
        name: 'SystemNotice',
        component: () => import('../views/system/notice/index.vue'),
        meta: { title: '通知公告', icon: 'notification' },
      },
      {
        path: 'error-code',
        name: 'SystemErrorCode',
        component: () => import('../views/system/errorCode/index.vue'),
        meta: { title: '错误码管理', icon: 'error-circle' },
      },
      {
        path: 'tenant',
        name: 'SystemTenant',
        component: () => import('../views/system/tenant/index.vue'),
        meta: { title: '租户管理', icon: 'cloud' },
      },
      {
        path: 'tenant-package',
        name: 'SystemTenantPackage',
        component: () => import('../views/system/tenantPackage/index.vue'),
        meta: { title: '租户套餐', icon: 'package' },
      },
      {
        path: 'sms/channel',
        name: 'SmsChannel',
        component: () => import('../views/system/sms/channel/index.vue'),
        meta: { title: '短信渠道', icon: 'chat' },
      },
      {
        path: 'sms/template',
        name: 'SmsTemplate',
        component: () => import('../views/system/sms/template/index.vue'),
        meta: { title: '短信模板', icon: 'edit' },
      },
      {
        path: 'sms/log',
        name: 'SmsLog',
        component: () => import('../views/system/sms/log/index.vue'),
        meta: { title: '短信日志', icon: 'time' },
      },
      {
        path: 'mail/account',
        name: 'MailAccount',
        component: () => import('../views/system/mail/account/index.vue'),
        meta: { title: '邮箱账号', icon: 'mail' },
      },
      {
        path: 'mail/template',
        name: 'MailTemplate',
        component: () => import('../views/system/mail/template/index.vue'),
        meta: { title: '邮件模板', icon: 'edit' },
      },
      {
        path: 'mail/log',
        name: 'MailLog',
        component: () => import('../views/system/mail/log/index.vue'),
        meta: { title: '邮件日志', icon: 'time' },
      },
      {
        path: 'operate-log',
        name: 'OperateLog',
        component: () => import('../views/system/operateLog/index.vue'),
        meta: { title: '操作日志', icon: 'browse' },
      },
      {
        path: 'login-log',
        name: 'LoginLog',
        component: () => import('../views/system/loginLog/index.vue'),
        meta: { title: '登录日志', icon: 'login' },
      },
      {
        path: 'oauth2',
        name: 'SystemOAuth2',
        component: () => import('../views/system/oauth2/index.vue'),
        meta: { title: '应用管理', icon: 'app' },
      },
      {
        path: 'online-user',
        name: 'OnlineUser',
        component: () => import('../views/system/onlineUser/index.vue'),
        meta: { title: '在线用户', icon: 'desktop' },
      },
    ],
  },
  {
    path: '/infra',
    component: () => import('../layout/index.vue'),
    meta: { title: '基础设施', icon: 'server' },
    children: [
      {
        path: 'codegen',
        name: 'InfraCodegen',
        component: () => import('../views/infra/codegen/index.vue'),
        meta: { title: '代码生成', icon: 'code' },
      },
      {
        path: 'codegen/edit',
        name: 'InfraCodegenEdit',
        component: () => import('../views/infra/codegen/index.vue'),
        meta: { title: '代码生成编辑', hidden: true },
      },
      {
        path: 'file',
        name: 'InfraFile',
        component: () => import('../views/infra/file/index.vue'),
        meta: { title: '文件管理', icon: 'folder' },
      },
      {
        path: 'file-config',
        name: 'InfraFileConfig',
        component: () => import('../views/infra/fileConfig/index.vue'),
        meta: { title: '文件配置', icon: 'setting' },
      },
      {
        path: 'job',
        name: 'InfraJob',
        component: () => import('../views/infra/job/index.vue'),
        meta: { title: '定时任务', icon: 'time' },
      },
      {
        path: 'config',
        name: 'InfraConfig',
        component: () => import('../views/infra/config/index.vue'),
        meta: { title: '配置管理', icon: 'list' },
      },
      {
        path: 'redis',
        name: 'InfraRedis',
        component: () => import('../views/infra/redis/index.vue'),
        meta: { title: 'Redis 监控', icon: 'chart' },
      },
      {
        path: 'api-access-log',
        name: 'InfraApiAccessLog',
        component: () => import('../views/infra/apiAccessLog/index.vue'),
        meta: { title: '访问日志', icon: 'browse' },
      },
      {
        path: 'api-error-log',
        name: 'InfraApiErrorLog',
        component: () => import('../views/infra/apiErrorLog/index.vue'),
        meta: { title: '错误日志', icon: 'error-circle' },
      },
      {
        path: 'db-doc',
        name: 'InfraDbDoc',
        component: () => import('../views/infra/dbDoc/index.vue'),
        meta: { title: '数据库文档', icon: 'file' },
      },
      {
        path: 'swagger',
        name: 'InfraSwagger',
        component: () => import('../views/infra/swagger/index.vue'),
        meta: { title: '系统接口', icon: 'link' },
      },
    ],
  },
  {
    path: '/bpm',
    component: () => import('../layout/index.vue'),
    meta: { title: '工作流', icon: 'flow' },
    children: [
      {
        path: 'model',
        name: 'BpmModel',
        component: () => import('../views/bpm/model/index.vue'),
        meta: { title: '流程模型', icon: 'chart' },
      },
      {
        path: 'form',
        name: 'BpmForm',
        component: () => import('../views/bpm/form/index.vue'),
        meta: { title: '流程表单', icon: 'file' },
      },
      {
        path: 'process-instance',
        name: 'BpmProcessInstance',
        component: () => import('../views/bpm/processInstance/index.vue'),
        meta: { title: '流程实例', icon: 'list' },
      },
      {
        path: 'task/todo',
        name: 'BpmTodoTask',
        component: () => import('../views/bpm/task/todo/index.vue'),
        meta: { title: '我的待办', icon: 'time' },
      },
      {
        path: 'task/done',
        name: 'BpmDoneTask',
        component: () => import('../views/bpm/task/done/index.vue'),
        meta: { title: '我的已办', icon: 'check-circle' },
      },
      {
        path: 'task/manager',
        name: 'BpmManagerTask',
        component: () => import('../views/bpm/task/manager/index.vue'),
        meta: { title: '全部任务', icon: 'list' },
      },
      {
        path: 'category',
        name: 'BpmCategory',
        component: () => import('../views/bpm/category/index.vue'),
        meta: { title: '流程分类', icon: 'folder' },
      },
      {
        path: 'user-group',
        name: 'BpmUserGroup',
        component: () => import('../views/bpm/group/index.vue'),
        meta: { title: '用户分组', icon: 'usergroup' },
      },
      {
        path: 'process-listener',
        name: 'BpmProcessListener',
        component: () => import('../views/bpm/processListener/index.vue'),
        meta: { title: '流程监听器', icon: 'notification' },
      },
      {
        path: 'process-expression',
        name: 'BpmProcessExpression',
        component: () => import('../views/bpm/processExpression/index.vue'),
        meta: { title: '流程表达式', icon: 'code' },
      },
    ],
  },
  {
    path: '/pay',
    component: () => import('../layout/index.vue'),
    meta: { title: '支付管理', icon: 'money-circle' },
    children: [
      {
        path: 'app',
        name: 'PayApp',
        component: () => import('../views/pay/app/index.vue'),
        meta: { title: '支付应用', icon: 'app' },
      },
      {
        path: 'channel',
        name: 'PayChannel',
        component: () => import('../views/pay/channel/index.vue'),
        meta: { title: '支付渠道', icon: 'link' },
      },
      {
        path: 'order',
        name: 'PayOrder',
        component: () => import('../views/pay/order/index.vue'),
        meta: { title: '支付订单', icon: 'order' },
      },
      {
        path: 'refund',
        name: 'PayRefund',
        component: () => import('../views/pay/refund/index.vue'),
        meta: { title: '退款订单', icon: 'rollback' },
      },
      {
        path: 'notify',
        name: 'PayNotify',
        component: () => import('../views/pay/notify/index.vue'),
        meta: { title: '支付通知', icon: 'notification' },
      },
      {
        path: 'wallet',
        name: 'PayWallet',
        component: () => import('../views/pay/wallet/index.vue'),
        meta: { title: '钱包管理', icon: 'wallet' },
      },
    ],
  },
  {
    path: '/report',
    component: () => import('../layout/index.vue'),
    meta: { title: '数据报表', icon: 'chart' },
    children: [
      {
        path: 'goview',
        name: 'GoView',
        component: () => import('../views/report/goview/index.vue'),
        meta: { title: '大屏设计器', icon: 'dashboard' },
      },
      {
        path: 'jmreport',
        name: 'JimuReport',
        component: () => import('../views/report/jmreport/index.vue'),
        meta: { title: '报表设计器', icon: 'file-chart' },
      },
    ],
  },
]
